package ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

public class Introduction extends JFrame {
    private JPanel MainPanel;
    private JPanel ButtonField;
    private JButton RegistrationButton;
    private JButton AuthorizationButton;
    private JLabel GreetingsLabel;
    private JLabel GreetingsDescriptionLabel;
    private JPanel IntroductionLabelsPanel;

    public Introduction() {
        //TODO randomized "welcome back" titles?
        $$$setupUI$$$();
        setContentPane(MainPanel);
        setTitle("Добро пожаловать!");
        setSize(700, 700);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);
    }

    public static void main(String[] args) {
        Introduction mainFrame = new Introduction();
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPanel = new JPanel();
        MainPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        MainPanel.setBackground(new Color(-1));
        ButtonField = new JPanel();
        ButtonField.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        MainPanel.add(ButtonField, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        RegistrationButton = new JButton();
        RegistrationButton.setBackground(new Color(-2299922));
        RegistrationButton.setFocusPainted(false);
        RegistrationButton.setForeground(new Color(-16777216));
        RegistrationButton.setSelected(true);
        RegistrationButton.setText("Регистрация");
        ButtonField.add(RegistrationButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, 1, GridConstraints.SIZEPOLICY_FIXED, new Dimension(100, 30), new Dimension(300, 30), new Dimension(500, 30), 0, false));
        AuthorizationButton = new JButton();
        AuthorizationButton.setBackground(new Color(-12743731));
        AuthorizationButton.setBorderPainted(false);
        AuthorizationButton.setFocusPainted(false);
        AuthorizationButton.setForeground(new Color(-1));
        AuthorizationButton.setMargin(new Insets(0, 0, 0, 0));
        AuthorizationButton.setSelected(true);
        AuthorizationButton.setText("Войти");
        ButtonField.add(AuthorizationButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, 1, GridConstraints.SIZEPOLICY_FIXED, new Dimension(100, 30), new Dimension(300, 30), new Dimension(500, 30), 0, false));
        final Spacer spacer1 = new Spacer();
        ButtonField.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(-1, 20), null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        ButtonField.add(spacer2, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(-1, 20), null, null, 0, false));
        IntroductionLabelsPanel = new JPanel();
        IntroductionLabelsPanel.setLayout(new GridLayoutManager(2, 3, new Insets(10, 10, 10, 10), -1, -1));
        MainPanel.add(IntroductionLabelsPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        GreetingsLabel = new JLabel();
        GreetingsLabel.setText("Добро пожаловать!");
        IntroductionLabelsPanel.add(GreetingsLabel, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        GreetingsDescriptionLabel = new JLabel();
        GreetingsDescriptionLabel.setIcon(new ImageIcon(getClass().getResource("/images/introduction.jpg")));
        GreetingsDescriptionLabel.setText("");
        IntroductionLabelsPanel.add(GreetingsDescriptionLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }

}
