package ui;

import classes.Response;
import classes.UserCredentials;
import classes.console.TextColor;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import ui.locale.Lang;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.IOException;
import java.util.Locale;

import static ui.Introduction.in;
import static ui.Introduction.out;

public class Registration extends JFrame {
    private JPanel MainRegisterPanel;
    private JButton BackButton;
    private JPanel RegisterPanel;
    private JLabel LoginLabel;
    private JLabel PasswordLabel;
    private JTextField LoginField;
    private JTextField PasswordField;
    private JButton RegistrationButton;
    private JLabel ErrorLabel;

    public Registration() {
        $$$setupUI$$$();
        setContentPane(MainRegisterPanel);
        setTitle("База данных фильмов - Регистрация");
        setSize(700, 700);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);
    }

    public static void main(String[] args) {
        Registration registrationFrame = new Registration();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        MainRegisterPanel = new JPanel();
        MainRegisterPanel.setLayout(new GridLayoutManager(3, 5, new Insets(0, 0, 0, 0), -1, -1));
        final Spacer spacer1 = new Spacer();
        MainRegisterPanel.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, 1, new Dimension(10, -1), new Dimension(10, -1), new Dimension(20, -1), 0, false));
        final Spacer spacer2 = new Spacer();
        MainRegisterPanel.add(spacer2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, 1, GridConstraints.SIZEPOLICY_FIXED, new Dimension(-1, 10), null, new Dimension(-1, 10), 0, false));
        BackButton.setBackground(new Color(-2299922));
        BackButton.setFocusPainted(false);
        BackButton.setForeground(new Color(-16777216));
        BackButton.setSelected(true);
        BackButton.setText("Назад");
        MainRegisterPanel.add(BackButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(80, 30), new Dimension(80, 30), new Dimension(100, 30), 0, false));
        RegisterPanel = new JPanel();
        RegisterPanel.setLayout(new GridLayoutManager(6, 1, new Insets(10, 10, 10, 10), -1, 3));
        MainRegisterPanel.add(RegisterPanel, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        RegisterPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-12743731)), "Регистрация", TitledBorder.CENTER, TitledBorder.BELOW_TOP, this.$$$getFont$$$(null, Font.BOLD, 14, RegisterPanel.getFont()), new Color(-12743731)));
        LoginLabel.setText("Логин");
        RegisterPanel.add(LoginLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        PasswordLabel.setText("Пароль");
        RegisterPanel.add(PasswordLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        RegisterPanel.add(LoginField, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        RegistrationButton.setBackground(new Color(-12743731));
        RegistrationButton.setBorderPainted(true);
        RegistrationButton.setFocusPainted(false);
        RegistrationButton.setFocusable(true);
        RegistrationButton.setForeground(new Color(-1));
        RegistrationButton.setMargin(new Insets(0, 0, 0, 0));
        RegistrationButton.setSelected(true);
        RegistrationButton.setText("Зарегистрироваться");
        RegisterPanel.add(RegistrationButton, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, 1, GridConstraints.SIZEPOLICY_FIXED, new Dimension(150, 30), new Dimension(200, 30), new Dimension(300, 30), 0, false));
        ErrorLabel = new JLabel();
        ErrorLabel.setEnabled(true);
        ErrorLabel.setFocusable(false);
        Font ErrorLabelFont = this.$$$getFont$$$(null, Font.BOLD, 12, ErrorLabel.getFont());
        if (ErrorLabelFont != null) ErrorLabel.setFont(ErrorLabelFont);
        ErrorLabel.setForeground(new Color(-4521984));
        ErrorLabel.setOpaque(false);
        ErrorLabel.setText("");
        ErrorLabel.setVisible(true);
        RegisterPanel.add(ErrorLabel, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        RegisterPanel.add(PasswordField, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final Spacer spacer3 = new Spacer();
        MainRegisterPanel.add(spacer3, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, 1, new Dimension(10, -1), new Dimension(10, -1), new Dimension(20, -1), 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainRegisterPanel;
    }

    private void createUIComponents() {
        Lang lang = new Lang();
        LoginLabel = new JLabel(lang.getString("enter_login"));
        PasswordLabel = new JLabel(lang.getString("enter_password"));

        BackButton = new JButton();
        BackButton.addActionListener(this::backButtonPressed);

        RegistrationButton = new JButton();
        RegistrationButton.addActionListener(this::registerButtonPressed);

        KeyListener enterListener = new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
            }

            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER)
                    RegistrationButton.doClick();
            }

            @Override
            public void keyReleased(KeyEvent e) {
            }
        };
        LoginField = new JTextField();
        LoginField.addKeyListener(enterListener);
        PasswordField = new JTextField();
        PasswordField.addKeyListener(enterListener);
    }

    private void registerButtonPressed(ActionEvent e) {
        String login = LoginField.getText();
        if (login.isBlank()) {
            printErrorMessage("Введите логин");
            return;
        }
        String password = PasswordField.getText();
        if (password.isEmpty()) {
            printErrorMessage("Введите пароль");
            return;
        }
        UserCredentials credentials = new UserCredentials(login, password);
        credentials.setRegistration(true);
        try {
            out.writeObject(credentials);
            out.flush();
            Response response = (Response) in.readObject();
            if (response.getCode() == 0) {
                ErrorLabel.setForeground(new Color(0, 80, 0));
                ErrorLabel.setText("Вход выполнен. Открывается база фильмов...");
                Introduction.mainActivityWindow = new MainActivity(credentials);
                this.dispose();
            } else printErrorMessage((String) response.getData());
        } catch (ClassNotFoundException error) {
            printErrorMessage(TextColor.yellow("Ошибка авторизации"));
        } catch (IOException ex) {
            printErrorMessage(TextColor.red("Ошибка ввода-вывода"));
        }
    }

    public void printErrorMessage(String message) {
        ErrorLabel.setText(message);
        ErrorLabel.setVisible(true);
    }

    private void backButtonPressed(ActionEvent e) {
        this.dispose();
        new Introduction();
    }
}
